# Question 1

In [1]:
import numpy as np
arr=np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

In [3]:
list_1 = []
list_2 = []

for i in range(5):
    x=int(input())
    list_1.append(x)
    
for i in range(5):
    x=int(input())
    list_2.append(x)
    
array_1 = np.array(list_1)
array_2 = np.array(list_2)
print(array_1)
print(array_2)

array = np.concatenate((array_1, array_2))
print(array)

sort_array = np.sort(array)
print(sort)




6
4
8
3
02
1
7
5
9
0
[6 4 8 3 2]
[1 7 5 9 0]
[6 4 8 3 2 1 7 5 9 0]
[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [4]:
array_3 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr_3.ndim)
print(arr_3.size)
print(arr_3.shape)


2
10
(2, 5)


# Question 4

In [13]:
print(np.arange(9))
print(np.arange(9).reshape(3,3))



[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Question 5

In [14]:
arr_1 = np.square([1, 2, 3, 4, 5])
arr_2 = np.square([6, 7, 8, 9, 10])
print(np.hstack((arr_1, arr_2)))
print(np.vstack((arr_1, arr_2)))

[  1   4   9  16  25  36  49  64  81 100]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Question 6

In [15]:


lst = [10, 20, 10, 30, 40, 40,"lst","lst",34.45,45.6,34.45] 
unique, counts = np.unique(lst, return_counts=True)
arr = np.asarray((unique, counts))

print(arr)

  

[['10' '20' '30' '34.45' '40' '45.6' 'lst']
 ['2' '1' '1' '2' '2' '1' '2']]
